### PR TITLE
Fix Alpha bugs for `attendance` `mark` and `unmark`

### LINKED ISSUE #108: `mark` shouldn't be able to work for non-member contacts

### LINKED ISSUE #109: `unmark` should not work for non-member contacts

### LINKED ISSUE #110: `unmark` shouldn't work for any contact that originally isn't present for the specified date
- now it displays successful unmarking for contacts who do not even have that date in their attendance
image

### LINKED ISSUE #122: bug: `mark` command allows attendance to be marked for a future date
Since the event has not occurred, it is unlikely that the client intended to mark the attendance for a future date. it is likely an error by the user but is not caught by the system. Users may mistakenly believe they have recorded attendance correctly and unaware of the inconsistency in the data.

perhaps some date validation can improve the user experience.

### LINKED ISSUE #123: bug: `mark` command contains grammatical error
image

-should be 'marked' 

-when a single person is marked it feels abit off to also display `'these people: [alex yeoh]'`. maybe can show `'this person: [alex yeoh]'` ? idk up to your discretion.

### LINKED ISSUE #124: bug: `mark` command does not provide feedback for a repeated command
The system does not inform users when a member's attendance has already been marked. users might be confused as they may mistakenly think that the member was not previously present and that their attendance was only just recorded.

Also suppose in the list [Alice, Bob] where Alice's attendance is already marked previously. if a user attempts to mark attendance for both Alice and bob, the system responds with both members 'successfully marked' which is misleading. because only Bob's attendance was updated in this operation and users might not realize that Alice's attendance was unchanged.

### LINKED ISSUE #137: Suggestion: Make `attendance` success message clearer
Screenshot 2024-10-30 at 23 58 23

Currently, `attendance` is structured to list out all the contacts with the `member` role. However, when used, the success message states "x people listed"

It would be clearer to explicitly specify "x members listed" to make it clear to the user that the command specifically targets members

### LINKED ISSUE #138: Bug: Minor grammar issue for `attendance`
Similar to Issue #134 

Steps to reproduce:
1. Have only 1 contact that has the role of Member
2. enter `atd`/`attendance`

Screenshot 2024-10-31 at 00 03 40

With 1 member, the plural "people" is still used in the success message. This should be changed to "person" or "member" instead

### LINKED ISSUE #139: Bug/Potential Spec Issue: `attendance` allows for users to input parameters
Similar to Issue https://github.com/AY2425S1-CS2103T-F11-2/tp/issues/135

Steps to reproduce:

1. Enter `attendance x`
On entering attendance with parameters, system proceeds as per normal. In the specs, it is stated that help takes in no parameters

If we want to restrict attendance to have no parameters, it might be good to display an error message like "attendance takes in no additional parameters", to make it clear to the user that adding additional parameters should not happen

### LINKED ISSUE #140: Suggestion/Spec Issue: `mark` does not inform user that certain telegram handles could not be found when marking multiple contacts
Steps to reproduce:
1. Enter `mark`, specifying a valid contact's telegram handle and a non-existent telegram handle, specifying a valid date
Screenshot 2024-10-31 at 00 13 02

Screenshot 2024-10-31 at 00 13 11

Currently, system only mentions that it successfully marked the attendance of the valid contact, and does not explicitly mention that the invalid handle could not be found

When using this functionality, if the user chains together many telegram handles in one command and makes a mistake entering 1 of the handles, he will not be informed that the handle could not be found, and might assume that everyone's attendance was marked properly, when this was not the case

### LINKED ISSUE #141: Suggestion/Spec Issue: `unmark` does not inform user that certain telegram handles could not be found when marking multiple contacts
Same issue as Issue #140

Currently, system only mentions that it successfully unmarked the attendance of the valid contact, and does not explicitly mention that the invalid handle could not be found

### PR DESCRIPTION
**Pull request by Rachelcoll**
Fixes #141, fixes #140, fixes #139, fixes #138, fixes #137, fixes #124, fixes #123, fixes #122, fixes #110, fixes #109, fixes #108 

1. Grammar errors for `attendance` and `mark` `unmark` message display:
    Replace "people" to "member(s)"

image

a8923db5587d54aebaa26fa8601a95a

2. Disallow extra user input to `attendance` command
image

3. Inform user when partial telegram handle is invalid for `mark` and `unmark`
When some of the user input telegram handles are valid and some are not, as long there exist one inexist telegram handle, it will output invalid telegram handles and won't mark/unmark any attendance
image

4. `mark` and `unmark` disallow future dates
9c363ffcb200ff14fa7d84620c29193

image

5. Handle members with attendance already marked for `mark` and members with attendance already unmarked for `unmark`
Under these situation, the command will normally mark/unmark the rest fo the members, but specifically listed out the unchanged members.
 
d3f40de03ee25ad9fdb5cbddcc34d12

image

6. Disallow attendance mark/unmark for non-member contacts
Throw an exception if the input telegram handle contains any non-member contact.
8fec0150e1414e341f4fc7a1735af72

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java [hunk 1]
```diff
@@ -102,24 +115,39 @@ public String toString() {
      * Find person with target telegram handle in current contact list
      * @param telegrams Target telegram handle to search in peopleList
      * @param peopleList All people in current contact list view
-     * @return Person with {@code telegram} if it exists, else return person not found
+     *      Add member to {@code membersToMarkAttendance} if their telegram handles is in input list;
```
Comment (superb-sushi) [inline src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java]: minor grammatical error (_handle_)

**Review by superb-sushi — APPROVED** [review]
LGTM!

**Review by weiliann — APPROVED** [review]
this pr looks good overall and resolves many issues so i will merge it first. but i notice some minor bugs and will open a new issue on it
