### PR TITLE
Fix error when input telegram contains invalid characters

### LINKED ISSUE #87: Bug when input invalid telegram handle to mark attendance
Currently when input telehandle that includes invalid characters like whitespace, the program will throw an nullpointer exception, since `AttendanceMarkingCommandParser` doesn't validate telegram handle before create `Telegram` object.

### PR DESCRIPTION
**Pull request by Rachelcoll**
Fixes #87

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java [hunk 1]
```diff
@@ -53,7 +54,12 @@ public AttendanceMarkingCommand parse(String args) throws ParseException {
                     MESSAGE_INVALID_COMMAND_FORMAT, MarkAttendanceCommand.MESSAGE_USAGE));
```
Comment (shizy) [inline src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java]: Since we are going to loop through the telegramKeywords and run each of them through the parseTelegram function, and since that function already checks for empty string, lines 50 to 55 might be redundant.

Also, I think the error message displayed from the parseTelegram check for empty strings provides more context than the generic MESSAGE_INVALID_COMMAND_FORMAT error message.

If you want, you could remove lines 50-55

File: src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java [hunk 2]
```diff
@@ -53,7 +54,12 @@ public AttendanceMarkingCommand parse(String args) throws ParseException {
...
         }
 
-        List<Telegram> telegrams = telegramKeywords.stream().map(String::trim).map(Telegram::new).toList();
+
+        List<Telegram> telegrams = new ArrayList<>();
+        for (String telegramStr : telegramKeywords) {
+            String trimmedTelegram = telegramStr.trim();
+            telegrams.add(ParserUtil.parseTelegram(trimmedTelegram));
```
Comment (shizy) [inline src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java:53]: Seems ok to me 👍

**Review by shizy — COMMENTED** [review]
Overall, changes LGTM

One thing I feel could be removed are lines 50-55, since the usage of `parseTelegram` already checks for empty strings, and also provides a more specific error message compared to the generic MESSAGE_INVALID_COMMAND_FORMAT message in the current empty input check

File: src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java (hunk 1 above)
Comment (Rachelcoll) [reply src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java]: Thanks for the review, removed the lines already.

**Review by superb-sushi — APPROVED** [review]
LGTM!

**Review by shizy — APPROVED** [review]
LGTM
