### PR TITLE
Fix alpha bugs to handle duplicate `f/`, `nf/` prefixes, enforce empty inputs after `f/` and `nf/`, and grammer issues

### LINKED ISSUE #134: Bug: Minor grammar issue for `find`
Steps to reproduce:
1. Use `find` for 1 specific contact
Screenshot 2024-10-30 at 23 39 16

Currently, regardless of number of people, plural `people` is used in the success message
If the `find` command only lists 1 person, we should change the "people" to "person"

### LINKED ISSUE #155: Suggestion: Favourite param `f/` allows irrlevant input
Currently when creating new contact, command like  `n/Mary p/12345677 e/test@test.com t/tele f/` and `n/Mary p/12345677 e/test@test.com t/tele f/uiadhudiw` will both successfully create a favourite contact, but `f/` is not supposed to followed by any user input, it maybe better to throw an exception if some string follows `/f` when creating or editing a contact.

### LINKED ISSUE #156: Bug: Favourite parameter `f/` and unfavourite parameter `nf/` allowed to appear multiple times in one command
The favourite param is allowed to appear multiple times in 1 command:
Steps to reproduce:
1. `add n/John Doe p/98765432 e/johnd@example.com t/johnDoe12 r/Exco Member f/ f/`
Screenshot 2024-11-03 at 15 50 47

This is currently considered a valid command by the system

Same thing happens when done in the `edit` command

The unfavourite param is also allowed to appear multiple times in 1 command:
Steps to reproduce:
1. `edit 1 nf/ nf/`
Screenshot 2024-11-03 at 15 52 44

This is also considered a valid command by the system

System behaviour should instead follow the following, which is implemented for the other params:
`Multiple values specified for the following single-valued field(s): n/`
Screenshot 2024-11-03 at 15 53 09

You can take inspiration from how those parameters are checked and restricted

### PR DESCRIPTION
**Pull request by yyihaoc**
Fixes #156, closes #155, fixes #134

#### Made changes stated in the title for:
`add`: No duplicate `f/`, require empty input tokenised under `f/`
`edit`: No duplicate `f/` and no duplicate `nf/`, require empty input tokenised under `f/`, require empty input tokenised under `nf/`
`find`: Require empty input tokenised under `f/`

#### Questions/Clarifications
Do we have to disallow duplicate `f/` in find? I was thinking if the find command is too long then the user might not be able to check back effectively if an `f/` is stated before so he/she can just add it multiple times.

### CODE REVIEW

**Review by shizy — APPROVED** [review]
LGTM! Regarding whether we should disallow repeat `f/`s, I guess since `find` allows repeated usages of other parameters e.g. `find n/john n/john`, I'm ok with allowing repeated uses of `f/` also

**Comment by weiliann** [comment]
currently if i dont use nf/ at the end of the command then i get an error. is this expected?

image

**Comment by weiliann** [comment]
currently the system is unreponsive when i try to find an invalid telegram handle. 
image

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -50,8 +50,14 @@ public CommandResult execute(Model model) {
 
         model.updateFilteredPersonList(rolePredicate.or(namePredicate).or(telegramPredicate).or(isFavouritePredicate));
 
-        return new CommandResult(
-                String.format(Messages.MESSAGE_PERSONS_LISTED_OVERVIEW, model.getFilteredPersonList().size()));
+        int numberOfPeopleListed = model.getFilteredPersonList().size();
+
+        if (numberOfPeopleListed == 0 || numberOfPeopleListed > 1) {
```
Comment (weiliann) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:55]: can this be simplified to >= 0

**Review by weiliann — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/FindCommand.java (hunk 1 above)
Comment (yyihaoc) [reply src/main/java/seedu/address/logic/commands/FindCommand.java:55]: I think here I try to say that if `numberOfPeopleListed` is 1 then the message return is person instead of people

**Comment by yyihaoc** [comment]
> currently if i dont use nf/ at the end of the command then i get an error. is this expected?
> 
> image

currently i dont intend for `add` to support the `nf/` prefix, but i think it makes sense to include it as well for consistency across the commands. thanks for pointing out, will fix this!

**Review by weiliann — APPROVED** [review]
