### PR TITLE
Alpha Bug Fixes

### LINKED ISSUE #106: Contacts with Multiple Roles - Lack of Separation in UI
image
- If contact has multiple roles, roles are not separated, but joined together to form one string

### LINKED ISSUE #107: `view` command should display "NA" instead of empty field under `attendance` for non-member contacts
indicate that field is not applicable for the current contact

### LINKED ISSUE #117: Ui Bug: Different Roles are listed without space in list view
When creating a member with multiple roles (eg. `a n/test2 t/... e/.. p/... r/Exco r/Member`, all the listed contact's roles are concatenated together, which can't distinguish from contact with role like `a n/test1 t/... e/.. p/... r/ExcoMember`.

image

### LINKED ISSUE #118: suggestion: `view` help message can be more helpful
image

not sure if the highlighted part is necessary for the users

### LINKED ISSUE #121: bug: `view` command shows a misleading error message
image

The `view t/` command accepts any string as input even if it is not a valid telegram handle. When a user inputs an invalid handle, the error message shows no user was found which is misleading because the user might think that the handle exists but just has no match.

maybe can reuse the telegram field validation and display a more specific error message like "invalid telegram handle" to help users catch typos

### LINKED ISSUE #126: Suggestion: Help message can be restricted to only vertical scrolling and not horizontal scrolling
Screenshot 2024-10-30 at 1 14 09 PM

Currently, the help message can be scrolled vertically, which may make it hard to see the entire message in a glance. Perhaps can wrap the text around?

### LINKED ISSUE #131: Suggestion: Add newlines in `view`'s invalid command error
Currently, the view command's invalid command error is displayed as such:
Screenshot 2024-10-30 at 23 07 49
Screenshot 2024-10-30 at 23 09 43

The view command's function is specified as one long line. It might be better to break it up into multiple lines

### LINKED ISSUE #132: Suggestion: GUI improvement for favourite property in `view`
Currently, in the `view`, a contact that is not a favourite contact has a display field of `>NOT_FAVOURITE CONTACT` while a favourite contact has a display field of `>FAVOURITE CONTACT`.
Screenshot 2024-10-30 at 23 13 58

This could be improved aesthetically. My suggestion would be to display the favourite status as a star.
Priority should be placed on improving the `NOT_FAVOURITE CONTACT` display.

### LINKED ISSUE #133: Suggestion: GUI improvement for favourite contacts in `list`
Currently, favourite contacts are displayed as such:
Screenshot 2024-10-30 at 23 31 12

The yellow does not contrast well with the white, which makes the text hard to read.
I would suggest toning down the colour, or changing the way favourite contacts are displayed (such as by using a star to indicate that the contact is favourited)

### LINKED ISSUE #150: bug: `view` command abruptly truncates `name` field when it exceeds current window size
Issue:
This behavior is not consistent with the UI on the main window

image

Expect:
Ellipses to be shown when the field is too long for the window size as per the main page

image

### LINKED ISSUE #154: Bug: Members with long names have their Attendance Status appear as an ellipsis (due to truncation)
image

### PR DESCRIPTION
**Pull request by superb-sushi**
Issues Fixed:
- Fixed view error message (too long / not useful —> added newline and removed irrelevant info) - Fixes #131; Fixes #118

- Added more specific error messages (e.g. less than 5 characters, contains illegal characters) - Fixes #121

- Roles now separated in list view - Fixes #106; Fixes #117

- Favourite contacts in list view colour toned down - Fixes #133

- View page `favourite` status now displayed as a Star - Fixes #132

- "NA" shown for non-members under `Attendance` field in `view` page, and members with no marked dates - Fixes #107 

- Truncation of Long Names in `view` page added - Fixes #150 

- Wrapping of `email` constraints message (for easier viewing) - Fixes #126 

- Fixed Truncation of `attendance` status in list view - Fixes #154

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 1]
```diff
@@ -21,10 +21,17 @@ public class ViewCommand extends Command {
     public static final String MESSAGE_NO_SUCH_TELEGRAM =
```
Comment (Rachelcoll) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: There is the variable `MESSAGE_INVALID_TELEGRAM = "Cannot find member(s) with telegram handle: %1$s";` in `Message.java` file, may be better to use that instead of duplicate one error message?

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 2]
```diff
@@ -21,10 +21,17 @@ public class ViewCommand extends Command {
...
             "There is no one in your address book with the telegram handle: @";
 
+    public static final String MESSAGE_TOO_SHORT_TELEGRAM =
+            "The telegram handle entered is too short (min 5 characters).";
+
+    public static final String MESSAGE_ILLEGAL_CHARACTERS_IN_TELEGRAM =
+            "The telegram handle entered contains illegal characters.\n"
+            + "Telegram handles should only contain letters, numbers and underscores.";
+
```
Comment (Rachelcoll) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: Just a suggestion, it may be better to move general error messages to `seedu/address/logic/Messages.java` file.

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 3]
```diff
@@ -21,10 +21,17 @@ public class ViewCommand extends Command {
...
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Finds one contact whose telegram handle "
-            + "matches the specified telegram handle (case-insensitive) and displays a new page which "
-            + "contains all the contact's information.\n"
+            + "matches the specified telegram handle (case-insensitive)\n"
+            + "and displays contains all the contact's information.\n"
```
Comment (Rachelcoll) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: Is the usage message supposed to be "and displays a new page which contains all the contacts' information"?

**Review by Rachelcoll — COMMENTED** [review]
LGTM!

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 4]
```diff
@@ -34,15 +35,53 @@ public ViewCommand(String tele) {
         this.tele = tele.toLowerCase();
     }
 
+    /**
+     * Checks if char array given contains any illegal characters (not letters, numbers or underscore)
+     * @param arr char array
+     * @return boolean value
+     */
+    public boolean containsIllegalCharacters(char[] arr) {
```
Comment (shizy) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: This method is likely redundant. It will probably be better to use the existing `isValidTelegram` public static method in the Telegram class, so that we have a sole point of change if we ever want to change the requirements

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 5]
```diff
@@ -34,15 +35,53 @@ public ViewCommand(String tele) {
...
+
+    /**
+     * Checks if telegram handle for this ViewCommand instance is at least 5
+     * characters long and that it contains no illegal characters. Otherwise
+     * throws relevant exception
+     * @throws CommandException
+     */
+    public void isValidHandle() throws CommandException {
+        char[] arr = this.tele.toCharArray();
+        if (arr.length < 5) {
```
Comment (shizy) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: Change this to make use of the public static `isValidTelegramLength` method in the Telegram class (this can only be done after PR #157 is merged in)

File: src/main/java/seedu/address/logic/Messages.java [hunk 6]
```diff
@@ -18,8 +18,13 @@ public class Messages {
     public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d people listed!";
     public static final String MESSAGE_DUPLICATE_FIELDS =
                 "Multiple values specified for the following single-valued field(s): ";
-    public static final String MESSAGE_INVALID_TELEGRAM = "Cannot find person with telegram handle: %1$s";
+    public static final String MESSAGE_INVALID_TELEGRAM = "Cannot find person with telegram handle: @%1$s";
+    public static final String MESSAGE_TOO_SHORT_TELEGRAM =
```
Comment (shizy) [inline src/main/java/seedu/address/logic/Messages.java]: Can change the `MESSAGE_TOO_SHORT_TELEGRAM` message to something like `MESSAGE_LENGTH_INVALID_TELEGRAM` - handle should be 5-32 characters long.

You can also consider using the public static `LENGTH_CONSTRAINTS` string in the Telegram class (once PR #157 is merged in)

**Review by shizy — CHANGES_REQUESTED** [review]
Mostly LGTM, but there are a few spots where there could be redundant code. Ideally, you can make use of the static methods/fields provided by the Telegram class to check for invalid inputs

File: src/main/java/seedu/address/logic/commands/ViewCommand.java (hunk 5 above)
Comment (shizy) [reply src/main/java/seedu/address/logic/commands/ViewCommand.java]: Now that #157 is merged in you can use the `isValidTelegramLength(String)` without needing to convert the tele string to array

**Review by shizy — APPROVED** [review]

**Comment by weiliann** [comment]
@superb-sushi i see many unresolved comments by zy and rx. i haven't looked at the code but are they resolved?

**Comment by superb-sushi** [comment]
> @superb-sushi i see many unresolved comments by zy and rx. i haven't looked at the code but are they resolved?

they've been resolved!

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 7]
```diff
@@ -34,15 +36,30 @@ public ViewCommand(String tele) {
         this.tele = tele.toLowerCase();
     }
 
+    /**
+     * Checks if telegram handle for this ViewCommand instance is at least 5
+     * characters long and that it contains no illegal characters. Otherwise
+     * throws relevant exception
+     * @throws CommandException
+     */
+    public void isValidHandle() throws CommandException {
```
Comment (weiliann) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: this feels like it should be in the `Telegram` class

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 8]
```diff
@@ -34,15 +36,30 @@ public ViewCommand(String tele) {
...
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        isValidHandle();
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
         List<Person> lastShownList = model.getFilteredPersonList();
         List<Person> p = lastShownList.stream().filter(person ->
                 person.getTelegram().value.toLowerCase().equals(this.tele)).toList();
         if (p.isEmpty()) {
-            throw new CommandException(MESSAGE_NO_SUCH_TELEGRAM + this.tele);
+            throw new CommandException(Messages.MESSAGE_INVALID_TELEGRAM + this.tele);
```
Comment (weiliann) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: why not use `String.format(MESSAGE_INVALID_TELEGRAM, this.tele)` ? I believe the MESSAGE_INVALID_TELEGRAM can accept an argument

**Review by weiliann — CHANGES_REQUESTED** [review]
just some minor stuff

**Review by weiliann — APPROVED** [review]
